### ISSUE TITLE
Gatsby site release #002

### ISSUE THREAD

**Issue by ninjasort** [benjifriedman/Online-Art-Archive#2]
Hey @benjifriedman, I created a list of the features you mentioned from Fiverr. Let me know if anything is missing here.

I'd be happy to finalize this scope and then start working on a new branch to get this updated for you.

### Pagination
- [x] Allow pagination
- [x] Add pagination buttons

### List of page slugs
- [x] On the home page, a list of the folder / page slugs as a list to be added to the homepage. (using `<SeriesList>`)

### Render other files from Google drive
- [x] Detect if a `.md` file is in the google drive folder and display the formatted contents of it before the photo loop
- [x] Being able to upload `.HEIC` files to google drive and have them display (automatically convert to webp or jpg?)

**Comment by ninjasort** [comment]
Hey @benjifriedman , I've pushed these changes. It looks like the .HEIC files are already converted on Google or are just coming up as mimeType = 'image/jpg' so I'm not sure if it's converting or what. But I added a converter in there in case you need it in the future.

All should be done for this release. Please test on your side and let me know if you see bugs.

**Comment by ninjasort** [comment]
- [x] pages generated from google drive folders aren't loading now (they go to the 404 page). 
- [x] also on the pagination, if I'm on a picture greater than index 5 and less than the last two, the pagination bar doesn't update. The ellipses just link to image 6

**Comment by ninjasort** [comment]
Ok @benjifriedman I pushed a fix for those 2 bugs. Let me know how it looks for you

**Comment by benjifriedman** [comment]
@ninjasort I'm seeing all the numbers listed now 👍 (it's showing all the numbers now, which isn't ideal / how I want it to be either, but still better. I'd ideally want it to show a maxium of like 9 "buckets" / links at any time.) The google drive generated pages aren't loading / populating with content, but don't go to 404 pages anymore. I haven't tested whether a .md or .mdx file in the folder populates either. They go to blank pages that show the layout components at least, but no content from google drive. Thank you also for putting this together so far and with this second round of adding features to the website! I hope I haven't been a hindrance with the changes I've made to the codebase in the midst of your work

**Comment by ninjasort** [comment]
Can you show me more of how your Google drive folder structure looks? Just want to confirm that the folders/files are being rendered properly.

**Comment by benjifriedman** [comment]
For sure. I have a folder called "Archive" on google drive (do you want the folder url?) and subfolders in it (just folders at that level). I have a couple subfolders with folders in them to test it out, but even the top level folder content isn't rendering now
